generator: admingenerator.generator.propel
params:
    model: Model\CmsContent
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for AdminBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: New object for AdminBundle
            display:
                "Fields":            [ cms_category, cms_types, title ]
            fields:
                cms_types:
                    formType:                   model
                    addFormOptions:
                        multiple:               true
                        class:                  Model\CmsType
                        # query:                  \Model\CmsTypeQuery::create()->orderById() 
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: CmsContent.title }|"
            display:
                "Fields":            [ cms_category, cms_types, title ]
            fields:
                cms_types:
                    formType:                   model
                    addFormOptions:
                        multiple:               true
                        class:                  Model\CmsType
                        query:                  \Model\CmsTypeQuery::create()->orderById() 
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: CmsContent.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
