# Specifics routes
AdminHomepage:
    pattern:  /
    defaults: { _controller: AppAdminBundle:Homepage\AdminHomepage:index }

# Admin generated routes
AppAdminBundle_admin_app_admin_bundle_CmsCategory:
    resource: "@AppAdminBundle/Controller/CmsCategory/"
    type:     admingenerator
    prefix:   /admin/app_admin_bundle/CmsCategory

AppAdminBundle_admin_app_admin_bundle_CmsContent:
    resource: "@AppAdminBundle/Controller/CmsContent/"
    type:     admingenerator
    prefix:   /admin/app_admin_bundle/CmsContent


# FOS user routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile